// <auto-generated />
using System;
using BackendAwSmartstay.API.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendAwSmartstay.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918070136_AddAccountSecurity")]
    partial class AddAccountSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Aggregates.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("amenities");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("host_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_hotels");

                    b.ToTable("hotels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jr. de la Unión 958",
                            Amenities = "[\"Wifi\",\"Restaurante\",\"Bar\"]",
                            City = "Lima",
                            Country = "Peru",
                            Description = "Historic hotel in the center of Lima.",
                            HostId = 1,
                            ImageUrl = "https://placehold.co/600x400/3498DB/FFFFFF?text=Bolivar",
                            Name = "Grand Hotel Bolivar",
                            Type = "Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "San Blas 123",
                            Amenities = "[\"Desayuno\",\"Wifi\",\"Gimnasio\"]",
                            City = "Cusco",
                            Country = "Peru",
                            Description = "Experience the mystic energy of the Andes.",
                            HostId = 1,
                            ImageUrl = "https://placehold.co/600x400/E67E22/FFFFFF?text=Andean",
                            Name = "Cusco Andean Lodge",
                            Type = "Lodge"
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Aggregates.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("amenities");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id")
                        .HasName("p_k_rooms");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("i_x_rooms__hotel_id");

                    b.HasIndex("RoomTypeId")
                        .HasDatabaseName("i_x_rooms__room_type_id");

                    b.ToTable("rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Amenities = "[\"Wifi\",\"TV\"]",
                            Description = "Room 101 - Standard view.",
                            HotelId = 1,
                            Price = 85.00m,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 102,
                            Amenities = "[\"Wifi\",\"TV\",\"Minibar\"]",
                            Description = "Room 102 - Plaza view with balcony.",
                            HotelId = 1,
                            Price = 150.00m,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 201,
                            Amenities = "[\"Jacuzzi\",\"Wifi\",\"Desayuno\",\"Chimenea\"]",
                            Description = "Suite 201 - Panoramic mountain view.",
                            HotelId = 2,
                            Price = 320.00m,
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_amenities_catalogs");

                    b.ToTable("amenities_catalogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            Name = "Wifi"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            Name = "Piscina"
                        },
                        new
                        {
                            Id = 3,
                            Category = "General",
                            Name = "Gimnasio"
                        },
                        new
                        {
                            Id = 4,
                            Category = "General",
                            Name = "Restaurante"
                        },
                        new
                        {
                            Id = 5,
                            Category = "General",
                            Name = "Parking"
                        },
                        new
                        {
                            Id = 6,
                            Category = "General",
                            Name = "Spa"
                        },
                        new
                        {
                            Id = 7,
                            Category = "General",
                            Name = "Bar"
                        },
                        new
                        {
                            Id = 8,
                            Category = "General",
                            Name = "Desayuno"
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Entities.HotelCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_hotel_categories");

                    b.ToTable("hotel_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Posada"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lodge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hostal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cabaña"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Resort"
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_room_types");

                    b.ToTable("room_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cozy room for solo travelers.",
                            Name = "Single Standard"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Spacious room for couples or business.",
                            Name = "Double Deluxe"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Luxury suite with best views.",
                            Name = "Presidential Suite"
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Bookings.Domain.Model.Aggregates.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("check_in_date");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("check_out_date");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("guest_email");

                    b.Property<int?>("GuestId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("guest_name");

                    b.Property<Guid?>("GuestProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("guest_profile_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_bookings");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("i_x_bookings_user_id");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("BackendAwSmartstay.API.IAM.Domain.Model.Aggregates.AccountToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_account_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_account_tokens__token_hash");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("i_x_account_tokens__user_id__purpose");

                    b.ToTable("account_tokens", (string)null);
                });

            modelBuilder.Entity("BackendAwSmartstay.API.IAM.Domain.Model.Aggregates.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued_at");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int")
                        .HasColumnName("token_version");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("i_x_refresh_tokens__family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_refresh_tokens__token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_refresh_tokens__user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("BackendAwSmartstay.API.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChainId")
                        .HasColumnType("int")
                        .HasColumnName("chain_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("FailedSignInAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_sign_in_attempts");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("token_version");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex(new[] { "Email" }, "i_x_users_email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.HasIndex(new[] { "Status" }, "i_x_users_status")
                        .HasDatabaseName("i_x_users_status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Payments.Domain.Model.Aggregates.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("card_holder_name");

                    b.Property<string>("CardNumberMasked")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("card_number_masked");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_method");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Profiles.Infrastructure.Persistence.EFC.Entities.EmployeeCodeSequence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("LastValue")
                        .HasColumnType("int")
                        .HasColumnName("last_value");

                    b.HasKey("Id")
                        .HasName("p_k_employee_code_sequences");

                    b.ToTable("employee_code_sequences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastValue = 0
                        });
                });

            modelBuilder.Entity("BackendAwSmartstay.Domain.Profiles.Domain.Model.Aggregates.GuestProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_guest_profiles");

                    b.HasIndex(new[] { "UserId" }, "ix_guest_profiles_user_id")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_profiles_user_id");

                    b.ToTable("guest_profiles", (string)null);
                });

            modelBuilder.Entity("BackendAwSmartstay.Domain.Profiles.Domain.Model.Aggregates.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("position");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("shift");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_staff_profiles");

                    b.HasIndex(new[] { "Code" }, "ix_staff_profiles_employee_code")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_profiles_employee_code");

                    b.HasIndex(new[] { "UserId" }, "ix_staff_profiles_user_id")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_profiles_user_id");

                    b.ToTable("staff_profiles", (string)null);
                });

            modelBuilder.Entity("BackendAwSmartstay.Domain.Profiles.Domain.Model.Entities.StaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("scope");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("staff_profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("p_k_staff_assignments");

                    b.HasIndex(new[] { "StaffProfileId" }, "ix_staff_assignments_staff_profile_id")
                        .HasDatabaseName("ix_staff_assignments_staff_profile_id");

                    b.HasIndex(new[] { "TargetId" }, "ix_staff_assignments_target_id")
                        .HasDatabaseName("ix_staff_assignments_target_id");

                    b.ToTable("staff_assignments", (string)null);
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Aggregates.Room", b =>
                {
                    b.HasOne("BackendAwSmartstay.API.Accommodations.Domain.Model.Aggregates.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_rooms_hotels__hotel_id");

                    b.HasOne("BackendAwSmartstay.API.Accommodations.Domain.Model.Entities.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_rooms_room_types__room_type_id");

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("BackendAwSmartstay.API.IAM.Domain.Model.Aggregates.AccountToken", b =>
                {
                    b.HasOne("BackendAwSmartstay.API.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_account_tokens_users__user_id");
                });

            modelBuilder.Entity("BackendAwSmartstay.API.IAM.Domain.Model.Aggregates.RefreshToken", b =>
                {
                    b.HasOne("BackendAwSmartstay.API.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_refresh_tokens_users__user_id");
                });

            modelBuilder.Entity("BackendAwSmartstay.Domain.Profiles.Domain.Model.Aggregates.GuestProfile", b =>
                {
                    b.OwnsOne("BackendAwSmartstay.Domain.Profiles.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("GuestProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("address_street");

                            b1.HasKey("GuestProfileId");

                            b1.ToTable("guest_profiles");

                            b1.WithOwner()
                                .HasForeignKey("GuestProfileId");
                        });

                    b.OwnsOne("BackendAwSmartstay.Domain.Profiles.Domain.Model.ValueObjects.IdentificationDocument", "Document", b1 =>
                        {
                            b1.Property<Guid>("GuestProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("document_number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("document_type");

                            b1.HasKey("GuestProfileId");

                            b1.HasIndex(new[] { "Type", "Number" }, "ix_guest_profiles_document")
                                .IsUnique();

                            b1.ToTable("guest_profiles");

                            b1.WithOwner()
                                .HasForeignKey("GuestProfileId");
                        });

                    b.OwnsOne("BackendAwSmartstay.Domain.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("GuestProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("email_address");

                            b1.HasKey("GuestProfileId");

                            b1.HasIndex(new[] { "Address" }, "ix_guest_profiles_email_address")
                                .IsUnique();

                            b1.ToTable("guest_profiles");

                            b1.WithOwner()
                                .HasForeignKey("GuestProfileId");
                        });

                    b.OwnsOne("BackendAwSmartstay.Domain.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("GuestProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("GuestProfileId");

                            b1.ToTable("guest_profiles");

                            b1.WithOwner()
                                .HasForeignKey("GuestProfileId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Document");

                    b.Navigation("Email");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("BackendAwSmartstay.Domain.Profiles.Domain.Model.Aggregates.StaffProfile", b =>
                {
                    b.OwnsOne("BackendAwSmartstay.Domain.Profiles.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("StaffProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("address_street");

                            b1.HasKey("StaffProfileId");

                            b1.ToTable("staff_profiles");

                            b1.WithOwner()
                                .HasForeignKey("StaffProfileId");
                        });

                    b.OwnsOne("BackendAwSmartstay.Domain.Profiles.Domain.Model.ValueObjects.IdentificationDocument", "Document", b1 =>
                        {
                            b1.Property<Guid>("StaffProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("document_number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("document_type");

                            b1.HasKey("StaffProfileId");

                            b1.ToTable("staff_profiles");

                            b1.WithOwner()
                                .HasForeignKey("StaffProfileId");
                        });

                    b.OwnsOne("BackendAwSmartstay.Domain.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("StaffProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("email_address");

                            b1.HasKey("StaffProfileId");

                            b1.HasIndex(new[] { "Address" }, "ix_staff_profiles_email_address")
                                .IsUnique();

                            b1.ToTable("staff_profiles");

                            b1.WithOwner()
                                .HasForeignKey("StaffProfileId");
                        });

                    b.OwnsOne("BackendAwSmartstay.Domain.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("StaffProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("StaffProfileId");

                            b1.ToTable("staff_profiles");

                            b1.WithOwner()
                                .HasForeignKey("StaffProfileId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Document");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("BackendAwSmartstay.Domain.Profiles.Domain.Model.Entities.StaffAssignment", b =>
                {
                    b.HasOne("BackendAwSmartstay.Domain.Profiles.Domain.Model.Aggregates.StaffProfile", null)
                        .WithMany("Assignments")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_staff_assignments_staff_profiles__staff_profile_id");

                    b.OwnsOne("BackendAwSmartstay.Domain.Profiles.Domain.Model.ValueObjects.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("StaffAssignmentId")
                                .HasColumnType("char(36)");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.HasKey("StaffAssignmentId");

                            b1.ToTable("staff_assignments");

                            b1.WithOwner()
                                .HasForeignKey("StaffAssignmentId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("BackendAwSmartstay.API.Accommodations.Domain.Model.Aggregates.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BackendAwSmartstay.Domain.Profiles.Domain.Model.Aggregates.StaffProfile", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
