using System.Security.Cryptography;
using System.Text.RegularExpressions;
using BackendAwSmartstay.Domain.Shared.Domain.Model.Exceptions;

namespace BackendAwSmartstay.API.Bookings.Domain.Model.ValueObjects;

/// <summary>
///     Human-readable unique code of a booking (US-51 scenario 2), e.g. <c>SS-7KQ4M2XP</c>: what the guest quotes at
///     the desk or on the phone. 8 random characters from an alphabet without look-alikes (32^8 ≈ 10^12 codes; the
///     database enforces uniqueness).
/// </summary>
public sealed partial record BookingCode
{
    private const string Alphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
    public const int MaxLength = 12;

    public BookingCode(string value)
    {
        var normalized = value?.Trim().ToUpperInvariant() ?? string.Empty;
        if (!Format().IsMatch(normalized))
            throw new DomainValidationException("A booking code looks like SS-7KQ4M2XP.");
        Value = normalized;
    }

    public string Value { get; }

    public static BookingCode New()
    {
        var chars = new char[8];
        for (var i = 0; i < chars.Length; i++)
            chars[i] = Alphabet[RandomNumberGenerator.GetInt32(Alphabet.Length)];
        return new BookingCode($"SS-{new string(chars)}");
    }

    public override string ToString() => Value;

    // Codes of bookings created before codes existed were generated by the migration from hexadecimal digits.
    [GeneratedRegex("^SS-[A-Z0-9]{8}$")]
    private static partial Regex Format();
}
